### ISSUE TITLE
No logging entries in widget "LoggerScreen" when app is build in release mode and installed via Testflight

### ISSUE THREAD

**Issue by KarinBerg** [itisnajim/logger_screen#2]
**Issue:**
When I start the app in debug mode on iOS I see the "LoggerScreen" with some log entries. When I build the app in release mode and distribute via Testflight I see als the "LoggerScreen" but without log entries. But the filters in the UI tell me that there are log entries. see screenshot [here](https://snipboard.io/bf059o.jpg)

**What I have done:**

This is how I build the LoggerScreen:
```
LoggerScreen(
      printer: appLoggerPrinter,
      trailingActions: [
        IconButton(
          icon: const Icon(Icons.clear_all),
          onPressed: appLoggerPrinter.clear,
        ),
      ],
    );
```
And this is how I configured the Logger and LoggerScreenPrinter. As you can see, I tell the Logger to also show logs in production (release) mode.
```
// Init logging
  final appLoggerPrinter = LoggerScreenPrinter(
    fileName: 'logs',
    encryptionKey: 'ThisIsAnExampleEncryptionKey123',
  );
  Logger.level = Level.debug;
  Logger.defaultFilter = () => ProductionFilter();
  Logger.defaultPrinter = () => appLoggerPrinter;
```

Can you tell me what I miss here? Why do I not see the log entries in the LoggerScreen in the Testflight version?

**Comment by itisnajim** [comment]
Does it work in a debug mode?
try to run the app in a release mode and in a real device and see what's there in the Xcode console..

**Comment by KarinBerg** [comment]
It's working now. Was my fault. I forgot to wrap the LoggerScreen with a Material widget like a Scaffold 🤦🏻‍♀️. 

```
Widget build(BuildContext context) {
    return Scaffold(
      body: LoggerScreen(
        printer: appLoggerPrinter,
        trailingActions: [
          IconButton(
            icon: const Icon(Icons.clear_all),
            onPressed: appLoggerPrinter.clear,
          ),
        ],
      ),
    );
  }

```
